name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted  # Usa self-hosted si tienes un runner propio
    strategy:
      matrix:
        node-version: [20.18.0]
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm cache clean --force

    - run: npm install

    #- run: |
     #   echo "NODE_ENV=production" >> $GITHUB_ENV

    - run: npm run build --if-present
      #env:
       # NODE_ENV: production

    - run: npm ls  # Verificar que todas las dependencias estén instaladas

    #- run: pm2 reload 0
