# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.18.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm cache clean --force
    - run: npm ci
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
      
    - name: Copy static files
      run: |
        cp -R ./.next/static ./.next/standalone/.next/static
 
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: .next/standalone
        include-hidden-files: true
